
<div class="alert alert-block alert-success" style="font-family:Times New Roman;color:#FFFFFF;background-color: #E7E7E7">
<h1 align="center"><span style="font-family:Times New Roman;color:#046D0B"><b>Big Data y Análisis de Datos usando Python con Inteligencia Artificial</b></span></h1>
</div>
<style>
table tr:last-child td:last-child {
  border-bottom-right-radius: 0.5rem;
}
</style>


<table align="center" style="font-size: 13px;">
<tr>
    <th align="left"><span style="font-family:Monospace;font-size: 12px;">Autor</span></th>
    <th align="left"><span style="font-family:Monospace;font-size: 12px;">:VR ROJAS</span></th>
</tr>
<tr>
    <th align="left"><span style="font-family:Monospace;font-size: 12px;">Email</span></th>
    <th align="left"><span style="font-family:Monospace;font-size: 12px;">:sacha.analytics@gmail.com</span></th>
</tr>
<tr>
    <th align="left"><span style="font-family:Monospace;font-size: 12px;">Web</span></th>
    <th align="left">:<a href="https://sacha-analytics.github.io/" style="font-family:Monospace;font-size: 13px;">sacha-analytics</a></th>
</tr>
</table>
<br>

# **3. Conceptos básicos de programación**

# **I. Fundamentos de programación básica**

## **1.1. Tipos de datos y variables**

### 1.1.1. Datos Categóricos

- Cadena (`string`): `"Hola"`

In [1]:
# data caracter
#----------------------
var_1 = "Hola"
var_2 = "2025"
var_3 = "15"

print("esto es el contenido de la variable var_1 = ",var_1, ", que es tipo no numerico")
print(type(var_1))
print(type(var_2))
print(type(var_3))

print(var_1)
print(var_2)
print(var_3)

print(var_1 + var_2)
print(var_1 + " " + var_2)

esto es el contenido de la variable var_1 =  Hola , que es tipo no numerico
<class 'str'>
<class 'str'>
<class 'str'>
Hola
2025
15
Hola2025
Hola 2025

### 1.1.2. Datos Numéricos

- Entero (`int`): `42`
- Flotante (`float`): `3.14`

In [2]:
# Datos y variables numericas
#-----------------------------
num_int = 25
num_float= 20.000001

print(type(num_int), type(num_float))

<class 'int'> <class 'float'>

### 1.1.3. Datos Booleanos

- Booleano (`bool`): `True` o `False`

In [3]:
abierto = True
cerrado = False

print(type(abierto), type(cerrado))
print(abierto)
print(cerrado)

<class 'bool'> <class 'bool'>
True
False

### 1.1.4. Datos Faltantes, nulos o no válidos
En Python, especialmente cuando trabajas con librerías de manipulación de datos como pandas y NumPy, existen varias formas de representar valores faltantes, nulos o no válidos. Los más comunes son:

- Especial (`NoneType`): `None`

In [4]:
sin_valor = None

print(type(sin_valor))
print(sin_valor)

<class 'NoneType'>
None

- Especial (`Not a Number`): `NaN`

In [5]:
import numpy as np

dato_no_valido = np.nan

print(type(dato_no_valido))
print(dato_no_valido)

<class 'float'>
nan

## **1.2. Operadores matemáticos**

In [6]:
# suma
suma = num_int + num_float
exponente = 5**2
div01 = 9/5
residuo_div01 = 9%5
div02 = 9//5

print("suma =",suma)
print(type(suma))
print("exp = ",exponente)
print("div01", div01)
print("residuo_div01",residuo_div01)
print(div02)

suma = 45.000001
<class 'float'>
exp =  25
div01 1.8
residuo_div01 4
1

In [7]:
# importar paquetes
import numpy as np


pi = np.pi
print(pi)

n_euler = np.e
print(n_euler)

3.141592653589793
2.718281828459045

In [8]:
# Funciones algebraicas
#----------------------------------
# funcion esponencial
y1 = n_euler**n_euler
print(y1)

# funcion valor absoluto
y2 = np.abs(-1*num_int)
print(y2)

#funcion raiz cuadrada
y3 = np.sqrt(num_int)
print(y3)

y4 = 125**(1/3)
print(y4)

# funcion logaritmo base 10
y5 = np.log10(10)
print(y5)

# funcion logaritmo base 2
y6 = np.log2(2)
print(y6)

# funcion logaritmo en base e
y7 = np.log(n_euler)
print(y7)

15.154262241479259
25
5.0
4.999999999999999
1.0
1.0
1.0

## **1.3. Operadores de comparación**

In [9]:
# operadores relacionales
# comparacion (==)
comp01 = num_int == num_float

# diferente (!=)
comp02 = num_int != num_float

# mayor que  (>)
comp03 = num_int > num_float

# menor que  (<)
comp04 = num_int < num_float

# mayor o igual que  (>=)
comp05 = num_int >= num_float

# menor o igual que  (<=)
comp06 = num_int <= num_float

print(type(comp01), comp01)
print(type(comp02), comp02)
print(type(comp03), comp03)
print(type(comp04), comp04)
print(type(comp05), comp05)
print(type(comp06), comp06)

<class 'bool'> False
<class 'bool'> True
<class 'bool'> True
<class 'bool'> False
<class 'bool'> True
<class 'bool'> False

## **1.4 Importar paquetes**

En Python, las librerías y los paquetes son conceptos fundamentales que permiten organizar, reutilizar y compartir código. Aunque a menudo se usan indistintamente, tienen significados técnicos específicos.

* **Paquetes**: Un paquete es una forma de organizar módulos de Python en directorios (carpetas). Un directorio se considera un paquete si contiene un archivo llamado` __init__.py`. Este archivo, que puede estar vacío, le dice a Python que el directorio debe ser tratado como un paquete. Los paquetes se utilizan para agrupar módulos relacionados y crear una estructura jerárquica, lo que facilita la gestión de proyectos grandes.

* **Librerías**: Una librería (o biblioteca) es un término más general que se refiere a una colección de código ya escrito que puedes usar en tu propio programa. Las librerías de Python se distribuyen comúnmente como paquetes, pero el término "librería" se enfoca en la funcionalidad que proporcionan. Por ejemplo, **Pandas** y **Numpy** son librerías muy populares que se instalan como paquetes.

<div align="center">
<img src="https://github.com/vrrp/sachabook_modulo1/blob/main/docs/images/preambulo/cajaHerramientas.png?raw=true" alt="" width="200" height="150">
</div>

```
paquete:
        aplicacion_01
        aplicacion_02
        . . . . . . .
        aplicacion_n
```

Formas de importar un paquete y sus aplicaciones

**Primera forma**
```
import paquete as pp

var = paquete.aplicacion_01(arg)
```

**Segunda forma**
```
import paquete as pp

var = pp.aplicacion_01(arg)
```

**Tercera forma**
```
from paquete import (aplicacion_01, aplicacion_04)

var_01 = aplicacion_01(arg)
var_02 = aplicacion_04(arg)
```

In [10]:
import math
import numpy as np

pi_math = math.pi
pi_np = np.pi
print(pi_math)
print(pi_np)

n_euler_math = math.e
n_euler_np = np.e
print(n_euler_math)
print(n_euler_np)

3.141592653589793
3.141592653589793
2.718281828459045
2.718281828459045

## **1.5. Funciones Algebraicas**

### 1.5.1. Exponencial

$y=f(x) = b^{x}$

$Si: b = 5, x = 2 $

$⇒ y=f(2)=5^2=25$

In [11]:
y1 = 5**2
display(y1)

25

### 1.5.2. Valor absoluto

$y = f(x) = |x|$

si: $x<0 ⇒ y = f(x) = |x| = (-1) \times x$

si: $x>0 → y = f(x) = |x| = x$

In [12]:
y2 = np.abs(-15)
print(y2)

15

### 1.5.3. Raíz cuadrada

$ y=f(x) = \sqrt{x} = x^\frac{1}{2}$

$ Si: x = 25 $
$⇒ y=f(25)=\sqrt{25}=5$

In [13]:
y3 = np.sqrt(25)
print(y3)

5.0

### **1.5.4. Raíz general**


$ y=f(x) = \sqrt[n]{x^m}= x^{\frac{m}{n}}$

$ Si: x = 125 $
$⇒ y=f(125)=\sqrt[3]{125}=\sqrt[3]{5^{3}}=5^{\frac{3}{3}}=5$

In [14]:
y4 = 125**(1/3)
print(y4)

4.999999999999999

### **1.5.5 Logaritmo**

$y = log_{b}x \Rightarrow x = b^y$

$Si: b=x ⇒b=b^y  \iff y = 1$

In [15]:
# funcion logaritmo de 10 en base 10
y5 = np.log10(10)
print(y5)

# funcion logaritmo de 2 en base 2
y6 = np.log2(2)
print(y6)

# funcion logaritmo de e en base e
y7 = np.log(n_euler_np)
print(y7)

1.0
1.0
1.0

## **1.6. Funciones: parte I**

In [16]:
def area_cuadrado(lado):
  area = lado**2
  return area

In [17]:
ac1 = area_cuadrado(4)
print(ac1)

16

# **II. Estructura de datos**

Una **estructura de datos** es una forma de organizar y almacenar información en la memoria de una computadora para que pueda ser utilizada de manera eficiente. En Python, estos objetos permiten manejar colecciones de datos, facilitando tareas como buscar, ordenar, insertar y eliminar elementos.

## **2.1. Cadenas**

Las cadenas en Python (`str`) son secuencias inmutables de caracteres Unicode que sirven para gestionar datos de texto. Al ser secuencias ordenadas, sus elementos se manipulan mediante posiciones numéricas, lo que permite extraer subtextos, medir extensiones y aplicar funciones nativas

<div align="center">
<img src="https://github.com/vrrp/sachabook_bigdata/blob/main/docs/images/ejemplo_cadena.png?raw=true" alt="" width="450" height="150">
</div>

In [18]:
# Estructuras tipo cadena de caracteres
var_cadena = "Hola a todos"

print(var_cadena)
print(len(var_cadena))

print(var_cadena[0:4])
print(type(var_cadena))

Hola a todos
12
Hola
<class 'str'>

In [19]:
departamentos_peru = "algunos departamentos de Perú son: Lima, Ica, Arequipa y Tacna"
print(departamentos_peru)
print(len(departamentos_peru))
print(departamentos_peru[35:39])
print(type(departamentos_peru))

algunos departamentos de Perú son: Lima, Ica, Arequipa y Tacna
62
Lima
<class 'str'>

In [20]:
separar_frase = departamentos_peru.split()
print(separar_frase)
print(type(separar_frase))

['algunos', 'departamentos', 'de', 'Perú', 'son:', 'Lima,', 'Ica,', 'Arequipa', 'y', 'Tacna']
<class 'list'>

In [21]:
print(list("python"))

['p', 'y', 't', 'h', 'o', 'n']

## **2.2. Listas**

Las listas son colecciones ordenadas y mutables, lo que significa que puedes añadir, eliminar o modificar elementos después de su creación. Son muy versátiles y se usan comúnmente para almacenar elementos del mismo tipo, aunque pueden contener datos de diferentes tipos.

<div align="center">
<img src="https://github.com/vrrp/sachabook_bigdata/blob/main/docs/images/ejemplo_lista.png?raw=true" alt="" width="400" height="120">
</div>

In [22]:
# listas
lista_01 = [7, "Hola", True, 2024.5]

print(lista_01.index(2024.5))

print(len(lista_01))
print(lista_01[0])

lista_01[3]= "Peru 2025"
print(lista_01)

print(type(lista_01[1]))

3
4
7
[7, 'Hola', True, 'Peru 2025']
<class 'str'>

## **2.3. Array 1D**

Un array 1D de NumPy es una estructura de datos fundamental en la biblioteca NumPy de Python, diseñada para almacenar una colección de elementos del mismo tipo de datos, como números enteros o de punto flotante. A diferencia de las listas estándar de Python, los arrays de NumPy están optimizados para operaciones matemáticas y científicas, lo que los hace significativamente más rápidos y eficientes en el manejo de grandes volúmenes de datos numéricos.

<div align="center">
<img src="https://github.com/vrrp/sachabook_bigdata/blob/main/docs/images/ejemplo_lista.png?raw=true" alt="" width="400" height="100">
</div>

In [23]:
import numpy as np

# array 1D: np.array()
array_meses_num = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(array_meses_num)
print(type(array_meses_num))
print(len(array_meses_num))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>
12

In [24]:
# array 1D: np.arange(val_i, num_vals, incremento)
array_arange01 = np.arange(-20, 10, 0.5)

print(array_arange01)
print(len(array_arange01))

[-20.  -19.5 -19.  -18.5 -18.  -17.5 -17.  -16.5 -16.  -15.5 -15.  -14.5
 -14.  -13.5 -13.  -12.5 -12.  -11.5 -11.  -10.5 -10.   -9.5  -9.   -8.5
  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5  -4.   -3.5  -3.   -2.5
  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5   2.    2.5   3.    3.5
   4.    4.5   5.    5.5   6.    6.5   7.    7.5   8.    8.5   9.    9.5]
60

In [25]:
# array 1D: np.zeros()
array_zeros01 = np.zeros(4)

print(array_zeros01)

print(type(array_zeros01))
print(len(array_zeros01))
print(np.ndim(array_zeros01))
print(np.shape(array_zeros01))

print(lista_01[1])
array_zeros01[2]==lista_01[1]

[0. 0. 0. 0.]
<class 'numpy.ndarray'>
4
1
(4,)
Hola

np.False_

## **2.4. Data Frame**

Un **DataFrame** es una estructura de datos bidimensional, similar a una hoja de cálculo o a una tabla de una base de datos. Se compone de filas y columnas, donde cada columna puede tener un tipo de dato diferente (números, texto, booleanos, etc.) y cada fila representa una observación o registro. Es uno de los objetos más importantes de Pandas y la base para el análisis y la manipulación de datos en Python.

---

**Descripción y características clave**

* **Estructura de tabla**: Un DataFrame se parece a una tabla de Excel o a un `SELECT` de una base de datos. Tiene **etiquetas de columna** (nombres para cada columna) y un **índice de fila** que permite acceder a los registros.

* **Heterogeneidad de datos**: A diferencia de los arrays de NumPy, donde todos los elementos deben ser del mismo tipo, cada columna en un DataFrame puede contener datos de un tipo distinto. Esto lo hace ideal para trabajar con datos del mundo real, que suelen ser una mezcla de números, texto, fechas, etc.

* **Manipulación de datos**: Pandas ofrece un conjunto de herramientas muy eficientes para trabajar con DataFrames, permitiendo realizar operaciones como:
    * **Filtrado y selección**: Se pueden seleccionar filas o columnas basándose en condiciones específicas.
    * **Limpieza de datos**: Manejar valores faltantes (`NaN`), eliminar duplicados o corregir errores.
    * **Análisis**: Realizar cálculos estadísticos (media, mediana, desviación estándar), agrupar datos, y unirlos con otros DataFrames.
    * **Entrada y salida (I/O)**: Es muy fácil leer datos desde archivos (CSV, Excel, JSON) y escribir resultados en los mismos formatos.

En resumen, el DataFrame de Pandas simplifica la manipulación y el análisis de datos complejos, proporcionando una estructura intuitiva y herramientas potentes para que los científicos de datos y los analistas trabajen de forma productiva.

<div align="center">
<img src="https://github.com/vrrp/sachabook_bigdata/blob/main/docs/images/ejemplo_dataframe.png?raw=true" alt="" width="450" height="200">
</div>

In [26]:
# importar paquete [pandas] como [pd]
import pandas as pd

In [27]:
lista_animales = ["fox", "kangaroo", "deer","spider","snale"]
array_legs     = np.array([4,2,4,8,np.nan])

display(lista_animales)
display(array_legs)

['fox', 'kangaroo', 'deer', 'spider', 'snale']

array([ 4.,  2.,  4.,  8., nan])

In [28]:
df_animales = pd.DataFrame({'animal': lista_animales,
                            'legs': array_legs})
display(df_animales)

     animal  legs
0       fox   4.0
1  kangaroo   2.0
2      deer   4.0
3    spider   8.0
4     snale   NaN

# **III. Estructuras de control de flujo**

In [29]:
def encontrar_nan(df):
    # Verificar valores NaN en cada columna
    nan_por_columna = df.isna().sum()

    # Verificar valores NaN en todo el DataFrame
    total_nan = df.isna().sum().sum()

    # Mostrar resultados
    print("DataFrame original:")
    print(df)
    print("\nValores NaN por columna:")
    print(nan_por_columna)
    print(f"\nTotal de valores NaN en el DataFrame: {total_nan}")

# Llamar a la función con el DataFrame
#encontrar_nan(df_excel)
#encontrar_nan(df_csv)

Las estructuras de control en Python son construcciones de programación que permiten modificar el flujo de ejecución de un programa. En lugar de ejecutar las instrucciones de forma secuencial de arriba a abajo, estas estructuras dirigen el programa para que tome decisiones, repita acciones o ejecute bloques de código específicos.

## **3.1. Condicionales: `if`, `else` y `elif`**

Las estructuras de control condicionales también denominadas estructuras de selección, permiten que el programa tome decisiones. El bloque de código sólo se ejecuta si se cumple una condición específica.

In [30]:
# condicionales: if, elif, else
var = 23

if type(var)==int:
  print("var es entero")
  print("segunda accion de if")
else:
  print("var no es un numero entero")

var es entero
segunda accion de if

In [31]:
# condicionales: if, elif, else
a = 7
b = 7

if a > b:
    print("(1)", a,">",b ,a > b)

elif a < b:
    print("(2)", a,"<",b ,a < b)

elif a == b:
    print("(3)", a,"==",b ,a == b)

(3) 7 == 7 True

## 3.2. **Bucle ó Loop: `for`**

Las estructuras de control tipo bucle (o loop) en Python son construcciones de código que permiten ejecutar un bloque de instrucciones de manera repetida. Su propósito principal es automatizar tareas que deben realizarse múltiples veces, ya sea un número fijo de veces o hasta que se cumpla una condición específica.

El bucle `for` se utiliza para iterar sobre una secuencia de elementos, como una lista, una tupla, un diccionario o una cadena de texto. La iteración se detiene automáticamente una vez que se han procesado todos los elementos de la secuencia.

Control de flujo: **for**


```
for arg01 in arg02:
    aplicacion_01
    aplicacion_02
       ........
    aplicacion_n
```

### 3.2.1 Uso de del bucle `for` en estructura de datos lista

```
lista_01 = ["hola", 2024, "mundo", 2024.5]
              |       |      |       |
              v       v      v       v
              0       1      2       3
```

In [32]:
print(lista_01[0])
print(lista_01[1])

7
Hola

In [33]:
n_elem = len(lista_01)
print(n_elem)

4

In [34]:
for i in range(n_elem):
  print(lista_01[i])

7
Hola
True
Peru 2025

### 3.2.2. Analisis exploratorio y procesamiento de la variable `lista_01`

In [35]:
for i in range(n_elem):
  if type(lista_01[i])==int:
    lista_01[i]= str(lista_01[i])
    print(lista_01[i])

7

In [36]:
print(lista_01)

['7', 'Hola', True, 'Peru 2025']

### 3.2.3. Uso de del bucle `for` en estructura de datos Data Frame

In [37]:
data = np.arange(0.0, 2.0, 0.1)
print(data)

temp_aire = 18*(1 + np.sin(2 * np.pi * data))
print(temp_aire)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]
[18.         28.58013454 35.11901729 35.11901729 28.58013454 18.
  7.41986546  0.88098271  0.88098271  7.41986546 18.         28.58013454
 35.11901729 35.11901729 28.58013454 18.          7.41986546  0.88098271
  0.88098271  7.41986546]

In [38]:
# Creando un data frame

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [39]:
df["temperatura"]= temp_aire
display(df)

    temperatura
0     18.000000
1     28.580135
2     35.119017
3     35.119017
4     28.580135
5     18.000000
6      7.419865
7      0.880983
8      0.880983
9      7.419865
10    18.000000
11    28.580135
12    35.119017
13    35.119017
14    28.580135
15    18.000000
16     7.419865
17     0.880983
18     0.880983
19     7.419865

In [40]:
df["datos_decimales"]=data
display(df)

    temperatura  datos_decimales
0     18.000000              0.0
1     28.580135              0.1
2     35.119017              0.2
3     35.119017              0.3
4     28.580135              0.4
5     18.000000              0.5
6      7.419865              0.6
7      0.880983              0.7
8      0.880983              0.8
9      7.419865              0.9
10    18.000000              1.0
11    28.580135              1.1
12    35.119017              1.2
13    35.119017              1.3
14    28.580135              1.4
15    18.000000              1.5
16     7.419865              1.6
17     0.880983              1.7
18     0.880983              1.8
19     7.419865              1.9

In [41]:
hr = 2.5*temp_aire +5.6

df["humedad_relativa"] = hr
display(df)

    temperatura  datos_decimales  humedad_relativa
0     18.000000              0.0         50.600000
1     28.580135              0.1         77.050336
2     35.119017              0.2         93.397543
3     35.119017              0.3         93.397543
4     28.580135              0.4         77.050336
5     18.000000              0.5         50.600000
6      7.419865              0.6         24.149664
7      0.880983              0.7          7.802457
8      0.880983              0.8          7.802457
9      7.419865              0.9         24.149664
10    18.000000              1.0         50.600000
11    28.580135              1.1         77.050336
12    35.119017              1.2         93.397543
13    35.119017              1.3         93.397543
14    28.580135              1.4         77.050336
15    18.000000              1.5         50.600000
16     7.419865              1.6         24.149664
17     0.880983              1.7          7.802457
18     0.880983              1.8          7.802457
19     7.419865              1.9         24.149664

In [42]:
print(df.iloc[5, 2]) # [fila, columna]

50.60000000000001

In [43]:
# numero total de elementos o medidas del data frame
print(df.size)

# dimensiones del data frame
print(df.shape)

# nombres de las columnas
print(df.columns)

60
(20, 3)
Index(['temperatura', 'datos_decimales', 'humedad_relativa'], dtype='object')

In [44]:
parte_df = df[["temperatura","humedad_relativa"]]

parte_df["txhr"] = df["temperatura"]*df["humedad_relativa"]
display(parte_df)

    temperatura  humedad_relativa         txhr
0     18.000000         50.600000   910.800000
1     28.580135         77.050336  2202.108979
2     35.119017         93.397543  3280.029936
3     35.119017         93.397543  3280.029936
4     28.580135         77.050336  2202.108979
5     18.000000         50.600000   910.800000
6      7.419865         24.149664   179.187255
7      0.880983          7.802457     6.873829
8      0.880983          7.802457     6.873829
9      7.419865         24.149664   179.187255
10    18.000000         50.600000   910.800000
11    28.580135         77.050336  2202.108979
12    35.119017         93.397543  3280.029936
13    35.119017         93.397543  3280.029936
14    28.580135         77.050336  2202.108979
15    18.000000         50.600000   910.800000
16     7.419865         24.149664   179.187255
17     0.880983          7.802457     6.873829
18     0.880983          7.802457     6.873829
19     7.419865         24.149664   179.187255

In [45]:
print(parte_df["temperatura"])

0     18.000000
1     28.580135
2     35.119017
3     35.119017
4     28.580135
5     18.000000
6      7.419865
7      0.880983
8      0.880983
9      7.419865
10    18.000000
11    28.580135
12    35.119017
13    35.119017
14    28.580135
15    18.000000
16     7.419865
17     0.880983
18     0.880983
19     7.419865
Name: temperatura, dtype: float64

In [46]:
display(parte_df.describe())

       temperatura  humedad_relativa         txhr
count    20.000000         20.000000    20.000000
mean     18.000000         50.600000  1315.800000
std      13.058573         32.646431  1282.509391
min       0.880983          7.802457     6.873829
25%       7.419865         24.149664   179.187255
50%      18.000000         50.600000   910.800000
75%      28.580135         77.050336  2202.108979
max      35.119017         93.397543  3280.029936

In [47]:
df.iloc[2,1]= np.nan
display(df)

    temperatura  datos_decimales  humedad_relativa
0     18.000000              0.0         50.600000
1     28.580135              0.1         77.050336
2     35.119017              NaN         93.397543
3     35.119017              0.3         93.397543
4     28.580135              0.4         77.050336
5     18.000000              0.5         50.600000
6      7.419865              0.6         24.149664
7      0.880983              0.7          7.802457
8      0.880983              0.8          7.802457
9      7.419865              0.9         24.149664
10    18.000000              1.0         50.600000
11    28.580135              1.1         77.050336
12    35.119017              1.2         93.397543
13    35.119017              1.3         93.397543
14    28.580135              1.4         77.050336
15    18.000000              1.5         50.600000
16     7.419865              1.6         24.149664
17     0.880983              1.7          7.802457
18     0.880983              1.8          7.802457
19     7.419865              1.9         24.149664

In [48]:
display(df.describe())

       temperatura  datos_decimales  humedad_relativa
count    20.000000        19.000000         20.000000
mean     18.000000         0.989474         50.600000
std      13.058573         0.580129         32.646431
min       0.880983         0.000000          7.802457
25%       7.419865         0.550000         24.149664
50%      18.000000         1.000000         50.600000
75%      28.580135         1.450000         77.050336
max      35.119017         1.900000         93.397543

In [49]:
display(df.head(n=5))

   temperatura  datos_decimales  humedad_relativa
0    18.000000              0.0         50.600000
1    28.580135              0.1         77.050336
2    35.119017              NaN         93.397543
3    35.119017              0.3         93.397543
4    28.580135              0.4         77.050336

In [50]:
# Usando un bucle for (menos eficiente para DataFrames grandes)
estaciones = []

for data in df["temperatura"]:
  if data > 28:
    estaciones.append("verano")
  else:
    estaciones.append(np.nan)

In [51]:
display(estaciones)

[nan,
 'verano',
 'verano',
 'verano',
 'verano',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'verano',
 'verano',
 'verano',
 'verano',
 nan,
 nan,
 nan,
 nan,
 nan]

In [52]:
df["estacion"] = estaciones

In [53]:
display(df.head(n=6))

   temperatura  datos_decimales  humedad_relativa estacion
0    18.000000              0.0         50.600000      NaN
1    28.580135              0.1         77.050336   verano
2    35.119017              NaN         93.397543   verano
3    35.119017              0.3         93.397543   verano
4    28.580135              0.4         77.050336   verano
5    18.000000              0.5         50.600000      NaN

In [54]:
display(df.describe())

       temperatura  datos_decimales  humedad_relativa
count    20.000000        19.000000         20.000000
mean     18.000000         0.989474         50.600000
std      13.058573         0.580129         32.646431
min       0.880983         0.000000          7.802457
25%       7.419865         0.550000         24.149664
50%      18.000000         1.000000         50.600000
75%      28.580135         1.450000         77.050336
max      35.119017         1.900000         93.397543

## **3.3. Funciones: parte II**

**Ejemplo**: Implementar la función convert_temp para convertir valores de temperatura de grados Celsius a la escala Kelvin y Fahrenheit, ecuaciones  {eq}`eq:c2k` y  {eq}`eq:c2f`, respectivamente.

$$
 K = °C + 273.15
$$(eq:c2k)

$$
 F = \frac{9}{5}\times°C +32
$$(eq:c2f)

In [55]:
def convert_temp(data, tipo):
  if tipo=="K":
    temp = data + 273.15

  elif tipo=="F":
    temp = (data) * 9/5 + 32

  return temp

### 3.3.1. Uso de función con un dato

In [56]:
display(convert_temp(100, "F"))

212.0

In [57]:
display(convert_temp(100, "F"))

212.0

### 3.3.2. Uso de función con una estructura de datos

In [58]:
temp_k = convert_temp(df["temperatura"], "K")
display(temp_k.head(n=6))

0    291.150000
1    301.730135
2    308.269017
3    308.269017
4    301.730135
5    291.150000
Name: temperatura, dtype: float64

In [59]:
df["temperatura_k"]= temp_k
display(df.head(n=6))

   temperatura  datos_decimales  humedad_relativa estacion  temperatura_k
0    18.000000              0.0         50.600000      NaN     291.150000
1    28.580135              0.1         77.050336   verano     301.730135
2    35.119017              NaN         93.397543   verano     308.269017
3    35.119017              0.3         93.397543   verano     308.269017
4    28.580135              0.4         77.050336   verano     301.730135
5    18.000000              0.5         50.600000      NaN     291.150000

## **3.4 Manejo, control y preprocesamiento de datos**

### 3.4.1. Contar datos errados ó faltantes

In [60]:
df_copia1 = df.copy()
display(df_copia1.head())

   temperatura  datos_decimales  humedad_relativa estacion  temperatura_k
0    18.000000              0.0         50.600000      NaN     291.150000
1    28.580135              0.1         77.050336   verano     301.730135
2    35.119017              NaN         93.397543   verano     308.269017
3    35.119017              0.3         93.397543   verano     308.269017
4    28.580135              0.4         77.050336   verano     301.730135

In [61]:
df_copia2 = df.copy()

In [62]:
def contar_nan(dataframe):
    # Number of NaNs per column
    nan_counts = dataframe.isna().sum()

    # Total number of rows in the DataFrame
    total_rows = len(dataframe)

    # Percentage of NaNs per column
    nan_porcentaje = (nan_counts / total_rows) * 100

    # Create a DataFrame to display both counts and percentages
    nan_summary = pd.DataFrame({
        'NaN Cantidad': nan_counts,
        'NaN Porcemtaje (%)': nan_porcentaje
    })

    return nan_summary

In [63]:
# Contar NaN en df_copia1
resultado_nan = contar_nan(df_copia1)
print("Resumen de valores NaN por columna en df_copia1:")
display(resultado_nan)

Resumen de valores NaN por columna en df_copia1:

                  NaN Cantidad  NaN Porcemtaje (%)
temperatura                  0                 0.0
datos_decimales              1                 5.0
humedad_relativa             0                 0.0
estacion                    12                60.0
temperatura_k                0                 0.0

### 3.4.2. Completar datos errados ó faltantes

In [64]:
def completar_nan(dataframe, metodo='ffill', valor=None):
    """
    Completa valores NaN en un DataFrame.
    metodo: 'ffill', 'bfill', o 'constante'
    valor: valor a usar si metodo='constante'
    """
    if metodo == 'constante':
        return dataframe.fillna(value=valor)
    elif metodo == 'ffill':
        return dataframe.ffill()
    elif metodo == 'bfill':
        return dataframe.bfill()
    else:
        return dataframe.fillna(method=metodo)

In [65]:
# Aplicando la función a df_copia1
df_completado = completar_nan(df_copia1, metodo='ffill')

print("Vista previa de df_copia1 completado (ffill):")
display(df_completado.head(n=6))

print("\nConteo de NaNs después de completar:")
display(df_completado.isna().sum())

Vista previa de df_copia1 completado (ffill):

   temperatura  datos_decimales  humedad_relativa estacion  temperatura_k
0    18.000000              0.0         50.600000      NaN     291.150000
1    28.580135              0.1         77.050336   verano     301.730135
2    35.119017              0.1         93.397543   verano     308.269017
3    35.119017              0.3         93.397543   verano     308.269017
4    28.580135              0.4         77.050336   verano     301.730135
5    18.000000              0.5         50.600000   verano     291.150000

Conteo de NaNs después de completar:

temperatura         0
datos_decimales     0
humedad_relativa    0
estacion            1
temperatura_k       0
dtype: int64

Explicación de los métodos `ffill` y `bfill` en la función `completar_nan`

Dentro de la función `completar_nan`, los métodos `ffill()` y `bfill()` se utilizan para rellenar los valores faltantes (`NaN`) en un DataFrame de `pandas` de la siguiente manera:

*   **`ffill()` (Forward Fill o Relleno Hacia Adelante)**:
    *   Este método propaga la **última observación válida hacia adelante** para rellenar los valores nulos (`NaN`).
    *   Es decir, si hay un `NaN`, `ffill` toma el valor de la celda inmediatamente anterior (superior) en la misma columna y lo usa para rellenar ese `NaN`.
    *   **Ejemplo**: Si una columna tiene los valores `[10, NaN, 20]`, después de aplicar `ffill`, se convertirá en `[10, 10, 20]`. El `NaN` se rellena con el `10` de la fila anterior.
    *   **Uso común**: Es útil en series de tiempo donde se asume que un valor permanece constante hasta que se registra una nueva observación.

*   **`bfill()` (Backward Fill o Relleno Hacia Atrás)**:
    *   Este método propaga la **próxima observación válida hacia atrás** para rellenar los valores nulos (`NaN`).
    *   En este caso, si hay un `NaN`, `bfill` toma el valor de la celda inmediatamente posterior (inferior) en la misma columna y lo usa para rellenar ese `NaN`.
    *   **Ejemplo**: Si una columna tiene los valores `[10, NaN, 20]`, después de aplicar `bfill`, se convertirá en `[10, 20, 20]`. El `NaN` se rellena con el `20` de la fila siguiente.
    *   **Uso común**: Puede ser adecuado cuando el valor faltante es mejor representado por una observación futura, o cuando se desea rellenar desde el final de la serie hacia el principio.

### 3.4.3. Completar datos faltantes en columnas numéricas específicas

La función `completar_nan_col` se encargará de identificar las columnas numéricas en un DataFrame y aplicar el método de interpolación especificado para rellenar los valores `NaN`.

**Métodos de interpolación de Pandas:**
`pandas.DataFrame.interpolate()` soporta varios métodos, los más comunes son:

*   **`'linear'`**: Rellena los valores NaN de forma lineal entre los valores válidos. Es el método por defecto y uno de los más utilizados.
*   **`'nearest'`**: Utiliza el valor válido más cercano (anterior o siguiente).
*   **`'zero'`**: Rellena con 0.
*   **`'slinear'`, `'quadratic'`, `'cubic'`**: Métodos basados en splines (curvas suaves). Requieren más puntos de datos y pueden ser útiles para datos que siguen una curva.
*   **`'polynomial'`**: Rellena utilizando un ajuste polinómico. Requiere especificar el `order` (grado del polinomio).
*   **`'spline'`**: Rellena utilizando una interpolación spline. Requiere especificar el `order`.
*   **`'pad'`, `'ffill'`**: Rellena hacia adelante usando el último valor válido.
*   **`'bfill'`**: Rellena hacia atrás usando el siguiente valor válido.

In [66]:
def completar_nan_col(dataframe, method='linear', **kwargs):

    """
    Completa valores NaN solo en columnas numéricas de un DataFrame
    utilizando el método de interpolación especificado.

    Args:
        dataframe (pd.DataFrame): El DataFrame de entrada.
        method (str): El método de interpolación a usar. Ej: 'linear', 'spline', 'polynomial'.
        **kwargs: Argumentos adicionales para el método `interpolate` (ej. `order` para 'polynomial'/'spline').

    Returns:
        pd.DataFrame: El DataFrame con los NaNs en columnas numéricas interpolados.
    """
    import scipy.interpolate as interpolate

    df_interpolado = dataframe.copy()
    numeric_cols = df_interpolado.select_dtypes(include=np.number).columns

    for col in numeric_cols:
        # Solo interpolar si la columna tiene NaNs
        if df_interpolado[col].isnull().any():
            df_interpolado[col] = df_interpolado[col].interpolate(method=method, **kwargs)
    return df_interpolado

Para demostrar la función, vamos a introducir más `NaNs` en `df_copia2` en columnas numéricas.

In [67]:
# Introducir NaNs adicionales para la demostración en df_copia2
df_copia2.loc[5, 'temperatura'] = np.nan
df_copia2.loc[10, 'humedad_relativa'] = np.nan
df_copia2.loc[15, 'temperatura_k'] = np.nan

print("Valores NaN en df_copia2 antes de la interpolación:")
display(contar_nan(df_copia2))

Valores NaN en df_copia2 antes de la interpolación:

                  NaN Cantidad  NaN Porcemtaje (%)
temperatura                  1                 5.0
datos_decimales              1                 5.0
humedad_relativa             1                 5.0
estacion                    12                60.0
temperatura_k                1                 5.0

Ahora aplicaremos la función `completar_nan_col` con diferentes métodos de interpolación.

In [68]:
# Aplicar interpolación 'linear'
df_linear_interpolated = completar_nan_col(df_copia2, method='linear')

print("\nDataFrame después de interpolación 'linear' (primeras 7 filas):")
display(df_linear_interpolated.head(7))

print("Valores NaN después de interpolación 'linear':")
display(contar_nan(df_linear_interpolated))

DataFrame después de interpolación 'linear' (primeras 7 filas):

   temperatura  datos_decimales  humedad_relativa estacion  temperatura_k
0    18.000000              0.0         50.600000      NaN     291.150000
1    28.580135              0.1         77.050336   verano     301.730135
2    35.119017              0.2         93.397543   verano     308.269017
3    35.119017              0.3         93.397543   verano     308.269017
4    28.580135              0.4         77.050336   verano     301.730135
5    18.000000              0.5         50.600000      NaN     291.150000
6     7.419865              0.6         24.149664      NaN     280.569865

Valores NaN después de interpolación 'linear':

                  NaN Cantidad  NaN Porcemtaje (%)
temperatura                  0                 0.0
datos_decimales              0                 0.0
humedad_relativa             0                 0.0
estacion                    12                60.0
temperatura_k                0                 0.0

In [69]:
# Aplicar interpolación 'polynomial' de orden 2
df_poly_interpolated = completar_nan_col(df_copia2, method='polynomial', order=2)

print("\nDataFrame después de interpolación 'polynomial' (orden 2, primeras 7 filas):")
display(df_poly_interpolated.head(7))

print("Valores NaN después de interpolación 'polynomial' (orden 2):")
display(contar_nan(df_poly_interpolated))

DataFrame después de interpolación 'polynomial' (orden 2, primeras 7 filas):

   temperatura  datos_decimales  humedad_relativa estacion  temperatura_k
0    18.000000              0.0         50.600000      NaN     291.150000
1    28.580135              0.1         77.050336   verano     301.730135
2    35.119017              0.2         93.397543   verano     308.269017
3    35.119017              0.3         93.397543   verano     308.269017
4    28.580135              0.4         77.050336   verano     301.730135
5    18.000410              0.5         50.600000      NaN     291.150000
6     7.419865              0.6         24.149664      NaN     280.569865

Valores NaN después de interpolación 'polynomial' (orden 2):

                  NaN Cantidad  NaN Porcemtaje (%)
temperatura                  0                 0.0
datos_decimales              0                 0.0
humedad_relativa             0                 0.0
estacion                    12                60.0
temperatura_k                0                 0.0

# **IV. Referencias**

**Libros y manuales**

- [Libro de estadisitica con python]( https://www.editorial-sciela.org/index.php/sciela/article/view/16/49)



- [Introducción a la teoria de probabilidades](https://ciladi.org/wp-content/uploads/Version_final_Introduccion-Probabilidad-Python-vf_Bayas-3.pdf)

  

- [Guía practica de análsis exploratorio de python](https://datos.gob.es/sites/default/files/doc/file/guia_eda_python.pdf)


**Cursos en linea**

- [Estadística W3School](https://www.w3schools.com/statistics/index.php)

- [Estadística con python](https://docs.python.org/es/3/library/statistics.html)

- [Kaggle](https://www.kaggle.com/code/saurav9786/statistics-for-data-scientists)

**Aplicaciones IA**

[Gemini iA](https://gemini.google.com), [DeepSeek](https://www.deepseek.com/), [Chat GPT](https://chatgpt.com/), [Claude IA](https://claude.ai/) y [Julius IA](https://julius.ai)